--/*
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Location CASCADE CONSTRAINTS;
DROP TABLE Facility CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE ResourceTbl CASCADE CONSTRAINTS;
DROP TABLE EventRequest CASCADE CONSTRAINTS;
DROP TABLE EventPlan CASCADE CONSTRAINTS;
DROP TABLE EventPlanLine CASCADE CONSTRAINTS;
--*/



CREATE TABLE Customer (
CustNo   VARCHAR2(8) ,
CustName VARCHAR2(100) NOT NULL,
Address  VARCHAR2(100) NOT NULL,
Internal CHAR(1) NOT NULL,
Contact  VARCHAR2(100) NOT NULL,
Phone    CHAR(8) NOT NULL,
City     VARCHAR2(50) NOT NULL,
State    CHAR(2) NOT NULL,
Zip      CHAR(5) NOT NULL,
CONSTRAINT customer_pk PRIMARY KEY (CustNo),
CONSTRAINT Internal_check CHECK (Internal IN ('Y','N'))
);

CREATE TABLE Facility 
(
FacNo VARCHAR2(8)  ,
FacName VARCHAR2(100) NOT NULL,
CONSTRAINT facility_pk PRIMARY KEY (FacNo),
CONSTRAINT facname_unique UNIQUE(FacName)
);

CREATE TABLE Location (
LocNo VARCHAR2(8)  NOT NULL,
FacNo VARCHAR2(8)  NOT NULL,
LocName VARCHAR2(100) NOT NULL,
CONSTRAINT location_pk PRIMARY KEY (LocNo),
CONSTRAINT location_facility_facno_fk FOREIGN KEY (FacNo) REFERENCES Facility(FacNo)
);

CREATE TABLE Employee (
EmpNo VARCHAR2(8)  NOT NULL,
EmpName VARCHAR2(100)  NOT NULL,
Department VARCHAR2(100)  NOT NULL,
Email VARCHAR2(100)  NOT NULL,
Phone CHAR(6)  NOT NULL,
CONSTRAINT employee_pk PRIMARY KEY (EmpNo)
);

CREATE TABLE ResourceTbl(
ResNo VARCHAR2(8) NOT NULL,
ResName VARCHAR2(100) NOT NULL,
Rate INTEGER NOT NULL,
CONSTRAINT resourcetbl_pk PRIMARY KEY (ResNo),
CONSTRAINT resourcetbl_ratecheck CHECK (Rate > 0)
);

CREATE TABLE EventRequest(
EventNo VARCHAR2(8) NOT NULL,
DateHeld DATE NOT NULL,
DateReq DATE NOT NULL,
FacNo VARCHAR2(8) NOT NULL,
CustNo VARCHAR2(8) NOT NULL,
DateAuth DATE,
Status VARCHAR(8) NOT NULL,
EstCost INTEGER NOT NULL,
EstAudience DECIMAL NOT NULL,
BudNo VARCHAR2(8),
CONSTRAINT eventr_pk PRIMARY KEY (EventNo),
CONSTRAINT eventr_customer_custno_fk FOREIGN KEY (CustNo) REFERENCES Customer(CustNo),
CONSTRAINT eventr_facility_facno_fk FOREIGN KEY (FacNo) REFERENCES Facility(FacNo),
CONSTRAINT eventr_Status_check CHECK (Status IN ('Pending', 'Approved','Denied')),
CONSTRAINT eventr_EstAudience_check CHECK (EstAudience > 0)
);

CREATE TABLE EventPlan(
PlanNo VARCHAR2(8) NOT NULL,
EventNo VARCHAR2(8) NOT NULL,
WorkDate DATE NOT NULL,
Notes VARCHAR2(100),
Activity VARCHAR2(10) NOT NULL,
EmpNo VARCHAR2(8),
CONSTRAINT eventp_pk PRIMARY KEY (PlanNO),
CONSTRAINT eventp_eventr_eventno_fk FOREIGN KEY (EventNo) REFERENCES EventRequest(EventNo),
CONSTRAINT eventp_employee_empno_fk FOREIGN KEY (EmpNo) REFERENCES Employee(EmpNo)
);

CREATE TABLE EventPlanLine(
PlanNo VARCHAR2(8) NOT NULL,
LineNo DECIMAL NOT NULL,
TimeStart DATE NOT NULL,
TimeEnd DATE NOT NULL,
NumberFld DECIMAL NOT NULL,
LocNo VARCHAR2(8) NOT NULL,
ResNo VARCHAR2(8) NOT NULL,
CONSTRAINT EventPl_pk PRIMARY KEY (PlanNo, LineNo),
CONSTRAINT EventPl_EventPlan_planNo_fk FOREIGN KEY (PlanNo) REFERENCES EventPlan(PlanNo),
CONSTRAINT EventPl_Location_LocNo_fk FOREIGN KEY (LocNo) REFERENCES Location(LocNo),
CONSTRAINT EventPl_Resource_ResNo_fk FOREIGN KEY (ResNo) REFERENCES ResourceTbl(ResNo),
CONSTRAINT EventPl_TimeS_TimeE_check CHECK (TimeStart < TimeEnd)
);

